package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"graphql-postgres/graph/model"
	"strconv"
)

// GetAreaProdOfImportantCrops is the resolver for the getAreaProdOfImportantCrops field.
func (r *queryResolver) GetAreaProdOfImportantCrops(ctx context.Context, year *string) ([]*model.AreaProdOfImportantCrops, error) {
	query := `SELECT "Year", "Area (Wheat)", "Production (Wheat)", "Area (Maize)", "Production (Maize)", "Area (Rice)", "Production (Rice)", "Area (Sugarcane)", "Production (Sugarcane)", "Area (Cotton)", "Production (Cotton)" FROM area_prod_of_important_crops`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AreaProdOfImportantCrops
	for rows.Next() {
		var item model.AreaProdOfImportantCrops
		err := rows.Scan(&item.Year, &item.AreaWheat, &item.ProductionWheat, &item.AreaMaize, &item.ProductionMaize, &item.AreaRice, &item.ProductionRice, &item.AreaSugarcane, &item.ProductionSugarcane, &item.AreaCotton, &item.ProductionCotton)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetAreaProductionKharifVegetablesAjk is the resolver for the getAreaProductionKharifVegetablesAJK field.
func (r *queryResolver) GetAreaProductionKharifVegetablesAjk(ctx context.Context, district *string, vegetable *string) ([]*model.AreaProductionKharifVegetablesAjk, error) {
	query := `SELECT "District", "Vegetable_ID", "Vegetable", "Area 2019 (hect)", "Production 2019 (tons)", "Area 2020 (hect)", "Production 2020 (tons)", "Area 2021 (hect)", "Production 2021 (tons)" FROM "area_production_khairf_vegetables_AJK_19_21" WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if district != nil {
		query += ` AND "District" = $` + string(rune(argCounter+48))
		args = append(args, *district)
		argCounter++
	}
	if vegetable != nil {
		query += ` AND "Vegetable" = $` + string(rune(argCounter+48))
		args = append(args, *vegetable)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AreaProductionKharifVegetablesAjk
	for rows.Next() {
		var item model.AreaProductionKharifVegetablesAjk
		err := rows.Scan(&item.District, &item.VegetableID, &item.Vegetable, &item.Area2019Hect, &item.Production2019Tons, &item.Area2020Hect, &item.Production2020Tons, &item.Area2021Hect, &item.Production2021Tons)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetAreaProductionPercentageSharePunjabCrops is the resolver for the getAreaProductionPercentageSharePunjabCrops field.
func (r *queryResolver) GetAreaProductionPercentageSharePunjabCrops(ctx context.Context, crop *string, year *string) ([]*model.AreaProductionPercentageSharePunjabCrops, error) {
	query := `SELECT "Indicators", "Crop_ID", "Crop", "2007-08", "2008-09", "2009-10", "2010-11", "2011-12", "2012-13", "2013-14", "2014-15", "2015-16", "2016-17", "2017-18", "2018-19", "2019-20" FROM area_production_percentage_share_punjab_crops_2007_20 WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if crop != nil {
		query += ` AND "Crop" = $` + string(rune(argCounter+48))
		args = append(args, *crop)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AreaProductionPercentageSharePunjabCrops
	for rows.Next() {
		var item model.AreaProductionPercentageSharePunjabCrops
		err := rows.Scan(&item.Indicators, &item.CropID, &item.Crop, &item.Year200708, &item.Year200809, &item.Year200910, &item.Year201011, &item.Year201112, &item.Year201213, &item.Year201314, &item.Year201415, &item.Year201516, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetAreaSownBySourceOfIrrigationSindh is the resolver for the getAreaSownBySourceOfIrrigationSindh field.
func (r *queryResolver) GetAreaSownBySourceOfIrrigationSindh(ctx context.Context, year *string) ([]*model.AreaSownBySourceOfIrrigationSindh, error) {
	query := `SELECT "Year", "Total", "Canal", "Well", "Tube Well", "Canal Well", "Canal Wells", "Others" FROM area_sown_by_source_of_irrigation_sindh`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AreaSownBySourceOfIrrigationSindh
	for rows.Next() {
		var item model.AreaSownBySourceOfIrrigationSindh
		err := rows.Scan(&item.Year, &item.Total, &item.Canal, &item.Well, &item.TubeWell, &item.CanalWell, &item.CanalWells, &item.Others)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetAreaSownIrrigatedImportantCropsPunjab is the resolver for the getAreaSownIrrigatedImportantCropsPunjab field.
func (r *queryResolver) GetAreaSownIrrigatedImportantCropsPunjab(ctx context.Context, crops *string) ([]*model.AreaSownIrrigatedImportantCropsPunjab, error) {
	query := `SELECT "Crops", "2011-12", "2012-13", "2013-14", "2014-15", "2015-16", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21" FROM area_sown_irrigated_important_crops_punjab`
	var args []interface{}
	if crops != nil {
		query += ` WHERE "Crops" = $1`
		args = append(args, *crops)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AreaSownIrrigatedImportantCropsPunjab
	for rows.Next() {
		var item model.AreaSownIrrigatedImportantCropsPunjab
		err := rows.Scan(&item.Crops, &item.Year201112, &item.Year201213, &item.Year201314, &item.Year201415, &item.Year201516, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920, &item.Year202021)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetAreaSownIrrigationSource is the resolver for the getAreaSownIrrigationSource field.
func (r *queryResolver) GetAreaSownIrrigationSource(ctx context.Context, year *string) ([]*model.AreaSownIrrigationSource, error) {
	query := `SELECT "Year", "Total Area Sown", "Un-Irrigated", "Total Irrigated", "Irrigated by Canals", "Irrigated by Wells", "Irrigated by Tubewells", "Irrigated by Canalwells", "Irrigated by Canal Tubewells", "Irrigated by Others Sources" FROM area_sown_irrigation_source`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AreaSownIrrigationSource
	for rows.Next() {
		var item model.AreaSownIrrigationSource
		err := rows.Scan(&item.Year, &item.TotalAreaSown, &item.UnIrrigated, &item.TotalIrrigated, &item.IrrigatedByCanals, &item.IrrigatedByWells, &item.IrrigatedByTubewells, &item.IrrigatedByCanalwells, &item.IrrigatedByCanalTubewells, &item.IrrigatedByOthersSources)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetAreaSownProdYieldWheatPunjab is the resolver for the getAreaSownProdYieldWheatPunjab field.
func (r *queryResolver) GetAreaSownProdYieldWheatPunjab(ctx context.Context, district *string) ([]*model.AreaSownProdYieldWheatPunjab, error) {
	query := `SELECT "Province/ Division/ District", "2007-08", "2008-09", "2009-10", "2010-11", "2011-12", "2012-13", "2013-14", "2014-15", "2015-16", "2016-17", "2017-18", "2018-19", "2019-20" FROM area_sown_prod_yield_wheat_punjab`
	var args []interface{}
	if district != nil {
		query += ` WHERE "Province/ Division/ District" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AreaSownProdYieldWheatPunjab
	for rows.Next() {
		var item model.AreaSownProdYieldWheatPunjab
		err := rows.Scan(&item.ProvinceDivisionDistrict, &item.Year200708, &item.Year200809, &item.Year200910, &item.Year201011, &item.Year201112, &item.Year201213, &item.Year201314, &item.Year201415, &item.Year201516, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetAreaSownProductionCropsCombinedPunjab is the resolver for the getAreaSownProductionCropsCombinedPunjab field.
func (r *queryResolver) GetAreaSownProductionCropsCombinedPunjab(ctx context.Context, year *string, crop *string) ([]*model.AreaSownProductionCropsCombinedPunjab, error) {
	query := `SELECT "Year", "Crop_ID", "Crop", "Total Area Sown (1000 Hects)", "Area (1000 Hects)", "Production (1000 Hects)", "Index of Area Sown (Base year 2010-11)", "Index of Production (Base year 2010-11)", "% Share of Area Sown" FROM area_sown_production_crops_combined_punjab_2010_21 WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if year != nil {
		query += ` AND "Year" = $1`
		args = append(args, *year)
		argCounter++
	}
	if crop != nil {
		query += ` AND "Crop" = $` + string(rune(argCounter+48))
		args = append(args, *crop)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AreaSownProductionCropsCombinedPunjab
	for rows.Next() {
		var item model.AreaSownProductionCropsCombinedPunjab
		err := rows.Scan(&item.Year, &item.CropID, &item.Crop, &item.TotalAreaSown1000Hects, &item.Area1000Hects, &item.Production1000Hects, &item.IndexOfAreaSownBaseYear201011, &item.IndexOfProductionBaseYear201011, &item.PercentShareOfAreaSown)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetAreaTreatedWithPesticidesCropsPunjab is the resolver for the getAreaTreatedWithPesticidesCropsPunjab field.
func (r *queryResolver) GetAreaTreatedWithPesticidesCropsPunjab(ctx context.Context, year *string) ([]*model.AreaTreatedWithPesticidesCropsPunjab, error) {
	query := `SELECT "Year", "Total Area", "Wheat", "Rice and Rice Nursery", "Cotton", "Maize", "Sugarcane", "Vegetables/Fruits", "Other Crops" FROM area_treated_with_pesticides_crops_punjab`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AreaTreatedWithPesticidesCropsPunjab
	for rows.Next() {
		var item model.AreaTreatedWithPesticidesCropsPunjab
		err := rows.Scan(&item.Year, &item.TotalArea, &item.Wheat, &item.RiceAndRiceNursery, &item.Cotton, &item.Maize, &item.Sugarcane, &item.VegetablesFruits, &item.OtherCrops)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetAvgRetailPriceFertilizer is the resolver for the getAvgRetailPriceFertilizer field.
func (r *queryResolver) GetAvgRetailPriceFertilizer(ctx context.Context, year *string) ([]*model.AvgRetailPriceFertilizer, error) {
	query := `SELECT "Year", "Urea", "AN/CAN (26%N)", "AS (21%N)", "NP (20:22)", "SSP (G) (18%P)", "DAP (18:46)", "SOP (50%K)" FROM avg_retail_price_fertilizer_50kg`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.AvgRetailPriceFertilizer
	for rows.Next() {
		var item model.AvgRetailPriceFertilizer
		err := rows.Scan(&item.Year, &item.Urea, &item.AnCan26n, &item.As21n, &item.Np2022, &item.SspG18p, &item.Dap1846, &item.Sop50k)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetCanalWithdrawlsPunjab is the resolver for the getCanalWithdrawlsPunjab field.
func (r *queryResolver) GetCanalWithdrawlsPunjab(ctx context.Context, year *string, season *string) ([]*model.CanalWithdrawlsPunjab, error) {
	query := `SELECT "Year", "Season_ID", "Season", "All Canals (Punjab)", "Five Linked Canals", "M.R. Link (Internal)", "Haveli Canals", "Panjnad Canals", "Central Bari Doab Canals", "Sutlej Valley Canals", "Thal Canals", "Taunsa Canals", "C.R.B.C." FROM canal_withdrawls_punjab WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if year != nil {
		query += ` AND "Year" = $1`
		args = append(args, *year)
		argCounter++
	}
	if season != nil {
		query += ` AND "Season" = $` + string(rune(argCounter+48))
		args = append(args, *season)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.CanalWithdrawlsPunjab
	for rows.Next() {
		var item model.CanalWithdrawlsPunjab
		err := rows.Scan(&item.Year, &item.SeasonID, &item.Season, &item.AllCanalsPunjab, &item.FiveLinkedCanals, &item.MrLinkInternal, &item.HaveliCanals, &item.PanjnadCanals, &item.CentralBariDoabCanals, &item.SutlejValleyCanals, &item.ThalCanals, &item.TaunsaCanals, &item.Crbc)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetChannelsLengthDivisionsPunjab is the resolver for the getChannelsLengthDivisionsPunjab field.
func (r *queryResolver) GetChannelsLengthDivisionsPunjab(ctx context.Context, division *string) ([]*model.ChannelsLengthDivisionsPunjab, error) {
	query := `SELECT "Division", "Main Canals or Branches", "Major Distributories", "Minor Distributories", "Supply Escape Channels", "Sub-Total", "Drains", "Grand Total" FROM channels_length_divisions_punjab_21`
	var args []interface{}
	if division != nil {
		query += ` WHERE "Division" = $1`
		args = append(args, *division)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.ChannelsLengthDivisionsPunjab
	for rows.Next() {
		var item model.ChannelsLengthDivisionsPunjab
		err := rows.Scan(&item.Division, &item.MainCanalsOrBranches, &item.MajorDistributories, &item.MinorDistributories, &item.SupplyEscapeChannels, &item.SubTotal, &item.Drains, &item.GrandTotal)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetConsumptionFertilizersNutrientsPak is the resolver for the getConsumptionFertilizersNutrientsPak field.
func (r *queryResolver) GetConsumptionFertilizersNutrientsPak(ctx context.Context, year *string) ([]*model.ConsumptionFertilizersNutrientsPak, error) {
	query := `SELECT "Year", "Kharif N", "Kharif P", "Kharif K", "Kharif All", "Rabi N", "Rabi P", "Rabi K", "Rabi All", "Total N", "Total P", "Total K", "Total All" FROM consumption_fertilizers_nutrients_pak_2008_18`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.ConsumptionFertilizersNutrientsPak
	for rows.Next() {
		var item model.ConsumptionFertilizersNutrientsPak
		err := rows.Scan(&item.Year, &item.KharifN, &item.KharifP, &item.KharifK, &item.KharifAll, &item.RabiN, &item.RabiP, &item.RabiK, &item.RabiAll, &item.TotalN, &item.TotalP, &item.TotalK, &item.TotalAll)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetConsumptionOfPesticides is the resolver for the getConsumptionOfPesticides field.
func (r *queryResolver) GetConsumptionOfPesticides(ctx context.Context, year *string) ([]*model.ConsumptionOfPesticides, error) {
	query := `SELECT "Year", "Quantity (M.T) Imports", "Quantity (M.T) Production", "Quantity (M.T) Total", "Value (Million Rs.)" FROM consumption_of_pesticides_2008_18`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.ConsumptionOfPesticides
	for rows.Next() {
		var item model.ConsumptionOfPesticides
		err := rows.Scan(&item.Year, &item.QuantityMTImports, &item.QuantityMTProduction, &item.QuantityMTTotal, &item.ValueMillionRs)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetCottonProductionPakistan is the resolver for the getCottonProductionPakistan field.
func (r *queryResolver) GetCottonProductionPakistan(ctx context.Context, year *string) ([]*model.CottonProductionPakistan, error) {
	query := `SELECT "Factor", "2016-17", "2017-18", "2018-19", "2019-20" FROM cotton_production_pakistan_2016_20`
	var args []interface{}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.CottonProductionPakistan
	for rows.Next() {
		var item model.CottonProductionPakistan
		err := rows.Scan(&item.Factor, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetCropAreaPunjab is the resolver for the getCropAreaPunjab field.
func (r *queryResolver) GetCropAreaPunjab(ctx context.Context, crop *string) ([]*model.CropAreaPunjab, error) {
	query := `SELECT "Crop", "Cropped Area", "%  of  Total" FROM crop_area_punjab_2020_21`
	var args []interface{}
	if crop != nil {
		query += ` WHERE "Crop" = $1`
		args = append(args, *crop)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.CropAreaPunjab
	for rows.Next() {
		var item model.CropAreaPunjab
		err := rows.Scan(&item.Crop, &item.CroppedArea, &item.PercentOfTotal)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetDistributionImprovedSeedsPunjab is the resolver for the getDistributionImprovedSeedsPunjab field.
func (r *queryResolver) GetDistributionImprovedSeedsPunjab(ctx context.Context, year *string) ([]*model.DistributionImprovedSeedsPunjab, error) {
	query := `SELECT "Year", "Wheat", "Paddy", "Cotton", "Maize", "Gram", "Potato", "Total (Met Ton)" FROM distribution_indeginous_improved_seeds_punjab`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.DistributionImprovedSeedsPunjab
	for rows.Next() {
		var item model.DistributionImprovedSeedsPunjab
		err := rows.Scan(&item.Year, &item.Wheat, &item.Paddy, &item.Cotton, &item.Maize, &item.Gram, &item.Potato, &item.TotalMetTon)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetFarmersTrainedCooperativeFarmingKpk is the resolver for the getFarmersTrainedCooperativeFarmingKpk field.
func (r *queryResolver) GetFarmersTrainedCooperativeFarmingKpk(ctx context.Context, month *string) ([]*model.FarmersTrainedCooperativeFarmingKpk, error) {
	query := `SELECT "Month", "Kohat", "D.I Khan", "Mansehra", "Hangu", "Mardan", "Tank", "Charsadda", "Swat", "Peshawar", "Shangla", "Haripur", "Bannu", "Chitral", "Nowshera", "Dir Upper", "Malakand", "Abbottabad", "Swabi", "Dir Lower", "Bunner", "Karak", "Lakki Marwat", "Battagram", "Torghar", "Kohistan" FROM farmers_trained_cooperative_farming_kpk`
	var args []interface{}
	if month != nil {
		query += ` WHERE "Month" = $1`
		args = append(args, *month)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.FarmersTrainedCooperativeFarmingKpk
	for rows.Next() {
		var item model.FarmersTrainedCooperativeFarmingKpk
		err := rows.Scan(&item.Month, &item.Kohat, &item.DiKhan, &item.Mansehra, &item.Hangu, &item.Mardan, &item.Tank, &item.Charsadda, &item.Swat, &item.Peshawar, &item.Shangla, &item.Haripur, &item.Bannu, &item.Chitral, &item.Nowshera, &item.DirUpper, &item.Malakand, &item.Abbottabad, &item.Swabi, &item.DirLower, &item.Bunner, &item.Karak, &item.LakkiMarwat, &item.Battagram, &item.Torghar, &item.Kohistan)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetFertilizerMachineryImpactKpk is the resolver for the getFertilizerMachineryImpactKpk field.
func (r *queryResolver) GetFertilizerMachineryImpactKpk(ctx context.Context, year *string, district *string) ([]*model.FertilizerMachineryImpactKpk, error) {
	query := `SELECT "Year", "Factors", "Sub-Factor", "Districts", "Amount" FROM fertilizer_machinery_impact_kpk_2016_17 WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if year != nil {
		query += ` AND "Year" = $1`
		args = append(args, *year)
		argCounter++
	}
	if district != nil {
		query += ` AND "Districts" = $2`
		args = append(args, *district)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.FertilizerMachineryImpactKpk
	for rows.Next() {
		var item model.FertilizerMachineryImpactKpk
		err := rows.Scan(&item.Year, &item.Factors, &item.SubFactor, &item.Districts, &item.Amount)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetFertilizerUsageProductionPunjab is the resolver for the getFertilizerUsageProductionPunjab field.
func (r *queryResolver) GetFertilizerUsageProductionPunjab(ctx context.Context, year *string, district *string) ([]*model.FertilizerUsageProductionPunjab, error) {
	query := `SELECT "Year", "Province", "Division", "District", "Usage (in 1000 nutirient tons)", "Area Sown Total (Wheat)", "Area Sown (Rice)", "Area Sown (Cotton)", "Area Sown (Sugarcane)", "Wheat Production ", "Rice Production ", "Cotton Production ", "Sugarcane Production", "Output/Acre (Wheat)", "Output/Acre (Rice)", "Output/Acre (Cotton)", "Output/Acre (Sugarcane)" FROM fertilizer_usage_production_punjab_2002_15 WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if year != nil {
		query += ` AND "Year" = $1`
		args = append(args, *year)
		argCounter++
	}
	if district != nil {
		query += ` AND "District" = $2`
		args = append(args, *district)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.FertilizerUsageProductionPunjab
	for rows.Next() {
		var item model.FertilizerUsageProductionPunjab
		err := rows.Scan(&item.Year, &item.Province, &item.Division, &item.District, &item.UsageIn1000NutrientTons, &item.AreaSownTotalWheat, &item.AreaSownRice, &item.AreaSownCotton, &item.AreaSownSugarcane, &item.WheatProduction, &item.RiceProduction, &item.CottonProduction, &item.SugarcaneProduction, &item.OutputAcreWheat, &item.OutputAcreRice, &item.OutputAcreCotton, &item.OutputAcreSugarcane)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetFertilizersSaleDistrictsPunjab is the resolver for the getFertilizersSaleDistrictsPunjab field.
func (r *queryResolver) GetFertilizersSaleDistrictsPunjab(ctx context.Context, district *string) ([]*model.FertilizersSaleDistrictsPunjab, error) {
	query := `SELECT "Division / District", "2015-16", "2016-17", "2017-18", "2018-19", "2019-20" FROM fertilizers_sale_districts_punjab_2015_20`
	var args []interface{}
	if district != nil {
		query += ` WHERE "Division / District" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.FertilizersSaleDistrictsPunjab
	for rows.Next() {
		var item model.FertilizersSaleDistrictsPunjab
		err := rows.Scan(&item.DivisionDistrict, &item.Year201516, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetFoodGrainsStorageCapacityPunjab is the resolver for the getFoodGrainsStorageCapacityPunjab field.
func (r *queryResolver) GetFoodGrainsStorageCapacityPunjab(ctx context.Context, district *string) ([]*model.FoodGrainsStorageCapacityPunjab, error) {
	query := `SELECT "Division / District", "House Type", "Silos/Bins/ Bini Shell", "Open Bulk Heads", "Total" FROM food_grains_storage_capacity_punjab`
	var args []interface{}
	if district != nil {
		query += ` WHERE "Division / District" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.FoodGrainsStorageCapacityPunjab
	for rows.Next() {
		var item model.FoodGrainsStorageCapacityPunjab
		err := rows.Scan(&item.DivisionDistrict, &item.HouseType, &item.SilosBinsBiniShell, &item.OpenBulkHeads, &item.Total)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetForestsProductsPakistan is the resolver for the getForestsProductsPakistan field.
func (r *queryResolver) GetForestsProductsPakistan(ctx context.Context, year *string) ([]*model.ForestsProductsPakistan, error) {
	query := `SELECT "Year", "Timber (Thousand cub. Meters)", "Firewood (Thousand cub. Meters)", "Total (Thousand cub. Meters)", "Timber  (Million Rupees)", "Firewood  (Million Rupees)", "Total  (Million Rupees)" FROM forests_products_pakistan_2008_18`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.ForestsProductsPakistan
	for rows.Next() {
		var item model.ForestsProductsPakistan
		err := rows.Scan(&item.Year, &item.TimberThousandCubMeters, &item.FirewoodThousandCubMeters, &item.TotalThousandCubMeters, &item.TimberMillionRupees, &item.FirewoodMillionRupees, &item.TotalMillionRupees)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetGeographyColumns is the resolver for the getGeographyColumns field.
func (r *queryResolver) GetGeographyColumns(ctx context.Context) ([]*model.GeographyColumns, error) {
	query := `SELECT f_table_catalog, f_table_schema, f_table_name, f_geography_column, coord_dimension, srid, type FROM geography_columns`

	rows, err := r.DB.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.GeographyColumns
	for rows.Next() {
		var item model.GeographyColumns
		err := rows.Scan(&item.FTableCatalog, &item.FTableSchema, &item.FTableName, &item.FGeographyColumn, &item.CoordDimension, &item.Srid, &item.Type)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetGeometryColumns is the resolver for the getGeometryColumns field.
func (r *queryResolver) GetGeometryColumns(ctx context.Context) ([]*model.GeometryColumns, error) {
	query := `SELECT f_table_catalog, f_table_schema, f_table_name, f_geometry_column, coord_dimension, srid, type FROM geometry_columns`

	rows, err := r.DB.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.GeometryColumns
	for rows.Next() {
		var item model.GeometryColumns
		err := rows.Scan(&item.FTableCatalog, &item.FTableSchema, &item.FTableName, &item.FGeometryColumn, &item.CoordDimension, &item.Srid, &item.Type)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetGroundTruthingSurveyAdb is the resolver for the getGroundTruthingSurveyADB field.
func (r *queryResolver) GetGroundTruthingSurveyAdb(ctx context.Context, province *string, district *string, season *string) ([]*model.GroundTruthingSurveyAdb, error) {
	query := `SELECT "ID", "Season", "Province", "District", "Date", "Latitude", "Longitude", "Code", "Land", "Description", "Stage" FROM "ground_truthing_survey_ADB" WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if province != nil {
		query += ` AND "Province" = $1`
		args = append(args, *province)
		argCounter++
	}
	if district != nil {
		query += ` AND "District" = $2`
		args = append(args, *district)
		argCounter++
	}
	if season != nil {
		query += ` AND "Season" = $3`
		args = append(args, *season)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.GroundTruthingSurveyAdb
	for rows.Next() {
		var item model.GroundTruthingSurveyAdb
		err := rows.Scan(&item.ID, &item.Season, &item.Province, &item.District, &item.Date, &item.Latitude, &item.Longitude, &item.Code, &item.Land, &item.Description, &item.Stage)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetKharifRabiIrrigatedCrop is the resolver for the getKharifRabiIrrigatedCrop field.
func (r *queryResolver) GetKharifRabiIrrigatedCrop(ctx context.Context, crop *string) ([]*model.KharifRabiIrrigatedCrop, error) {
	query := `SELECT "Crop", "Total in 2018-19", "Irrigated in 2018-19", "Total in 2019-20", "Irrigated in 2019-20", "Total in 2020-21", "Irrigated 2020-21" FROM kharif_rabi_irrigated_crop_total_irrigated_area_2018_21`
	var args []interface{}
	if crop != nil {
		query += ` WHERE "Crop" = $1`
		args = append(args, *crop)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.KharifRabiIrrigatedCrop
	for rows.Next() {
		var item model.KharifRabiIrrigatedCrop
		err := rows.Scan(&item.Crop, &item.TotalIn201819, &item.IrrigatedIn201819, &item.TotalIn201920, &item.IrrigatedIn201920, &item.TotalIn202021, &item.Irrigated202021)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetLandUtilizationStatisticsPunjab is the resolver for the getLandUtilizationStatisticsPunjab field.
func (r *queryResolver) GetLandUtilizationStatisticsPunjab(ctx context.Context, year *string, district *string) ([]*model.LandUtilizationStatisticsPunjab, error) {
	query := `SELECT "Year", "Province/ Division/ District", "Geographical Area", "Reported Area", "Total Cultivated Area", "Current Fallows Cultivated Area", "Net Area Sown ", "Total Cropped Area", "Area Sown more than once", "Total Uncultivated Area", "Culturable waste Uncultivated Area", "Forest Uncultivated Area", "Not available for cultivation" FROM land_utilization_statistics_districts_punjab_2007_20 WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if year != nil {
		query += ` AND "Year" = $1`
		args = append(args, *year)
		argCounter++
	}
	if district != nil {
		query += ` AND "Province/ Division/ District" ILIKE $2`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.LandUtilizationStatisticsPunjab
	for rows.Next() {
		var item model.LandUtilizationStatisticsPunjab
		err := rows.Scan(&item.Year, &item.ProvinceDivisionDistrict, &item.GeographicalArea, &item.ReportedArea, &item.TotalCultivatedArea, &item.CurrentFallowsCultivatedArea, &item.NetAreaSown, &item.TotalCroppedArea, &item.AreaSownMoreThanOnce, &item.TotalUncultivatedArea, &item.CulturableWasteUncultivatedArea, &item.ForestUncultivatedArea, &item.NotAvailableForCultivation)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetLoansDisbursedZaraiTaraqiatBank is the resolver for the getLoansDisbursedZaraiTaraqiatBank field.
func (r *queryResolver) GetLoansDisbursedZaraiTaraqiatBank(ctx context.Context, purpose *string) ([]*model.LoansDisbursedZaraiTaraqiatBank, error) {
	query := `SELECT "Purpose", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21" FROM loans_disbursed_zarai_taraqiat_bank_punjab`
	var args []interface{}
	if purpose != nil {
		query += ` WHERE "Purpose" = $1`
		args = append(args, *purpose)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.LoansDisbursedZaraiTaraqiatBank
	for rows.Next() {
		var item model.LoansDisbursedZaraiTaraqiatBank
		err := rows.Scan(&item.Purpose, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920, &item.Year202021)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetMauzzasCroppedAreaPunjab is the resolver for the getMauzzasCroppedAreaPunjab field.
func (r *queryResolver) GetMauzzasCroppedAreaPunjab(ctx context.Context, district *string) ([]*model.MauzzasCroppedAreaPunjab, error) {
	query := `SELECT "Division / District", "Number of Mauzas", "Cropped Area(1000 Hectares)" FROM mauzzas_cropped_area_punjab_2019_20`
	var args []interface{}
	if district != nil {
		query += ` WHERE "Division / District" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.MauzzasCroppedAreaPunjab
	for rows.Next() {
		var item model.MauzzasCroppedAreaPunjab
		err := rows.Scan(&item.DivisionDistrict, &item.NumberOfMauzas, &item.CroppedArea1000Hectares)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetPercentageDistributionWheatPunjab is the resolver for the getPercentageDistributionWheatPunjab field.
func (r *queryResolver) GetPercentageDistributionWheatPunjab(ctx context.Context, district *string) ([]*model.PercentageDistributionWheatPunjab, error) {
	query := `SELECT "Province/ Division/ District", "2007-08", "2008-09", "2009-10", "2010-11", "2011-12", "2012-13", "2013-14", "2014-15", "2015-16", "2016-17", "2017-18", "2018-19", "2019-20" FROM percentage_distribution_wheat_districts_punjab_2009_20`
	var args []interface{}
	if district != nil {
		query += ` WHERE "Province/ Division/ District" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.PercentageDistributionWheatPunjab
	for rows.Next() {
		var item model.PercentageDistributionWheatPunjab
		err := rows.Scan(&item.ProvinceDivisionDistrict, &item.Year200708, &item.Year200809, &item.Year200910, &item.Year201011, &item.Year201112, &item.Year201213, &item.Year201314, &item.Year201415, &item.Year201516, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetPredictionCropYieldRiskPunjab is the resolver for the getPredictionCropYieldRiskPunjab field.
func (r *queryResolver) GetPredictionCropYieldRiskPunjab(ctx context.Context, district *string) ([]*model.PredictionCropYieldRiskPunjab, error) {
	query := `SELECT "Division / District", "Wheat", "Gram", "Barley", "Potato", "Onion", "Canola", "Rapeseed and Mustard", "Masoor crop", "Mattar (Peas)", "Other Rabi Pulses", "Garlic", "Tabacco", "Linseed", "Corriander", "Mattar (green)", "Carrot", "Tomato", "Turnip", "Cauliflower", "Other Vegitables", "Guava", "Banana", "Grapefruit", "Kinnu", "Lemon", "Mandrine", "Orange", "Musumbi", "Sour Lime", "Sour Orange", "Sweet Lime", "Other Citrus", "Ber", "Loquat", "Mulbery", "Other Rabi fruits", "Barseem", "Lucern", "Others" FROM prediction_crop_yield_identify_risk_punjab`
	var args []interface{}
	if district != nil {
		query += ` WHERE "Division / District" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.PredictionCropYieldRiskPunjab
	for rows.Next() {
		var item model.PredictionCropYieldRiskPunjab
		err := rows.Scan(&item.DivisionDistrict, &item.Wheat, &item.Gram, &item.Barley, &item.Potato, &item.Onion, &item.Canola, &item.RapeseedAndMustard, &item.MasoorCrop, &item.MattarPeas, &item.OtherRabiPulses, &item.Garlic, &item.Tabacco, &item.Linseed, &item.Corriander, &item.MattarGreen, &item.Carrot, &item.Tomato, &item.Turnip, &item.Cauliflower, &item.OtherVegetables, &item.Guava, &item.Banana, &item.Grapefruit, &item.Kinnu, &item.Lemon, &item.Mandrine, &item.Orange, &item.Musumbi, &item.SourLime, &item.SourOrange, &item.SweetLime, &item.OtherCitrus, &item.Ber, &item.Loquat, &item.Mulberry, &item.OtherRabiFruits, &item.Barseem, &item.Lucern, &item.Others)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetPriceWheatCities is the resolver for the getPriceWheatCities field.
func (r *queryResolver) GetPriceWheatCities(ctx context.Context, city *string) ([]*model.PriceWheatCities, error) {
	query := `SELECT "Commodity Item", "Unit (kg)", "City", "Dec 2020 Prices (Rs.)", "Sept 2021  Prices (Rs.)", "Dec 2021  Prices (Rs.)", "% Change in Dec 2021 Over Dec 2020", "% Change in Dec 2021 Over Sept 2021" FROM price_wheat_cities_2020_21`
	var args []interface{}
	if city != nil {
		query += ` WHERE "City" = $1`
		args = append(args, *city)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.PriceWheatCities
	for rows.Next() {
		var item model.PriceWheatCities
		err := rows.Scan(&item.CommodityItem, &item.UnitKg, &item.City, &item.Dec2020PricesRs, &item.Sept2021PricesRs, &item.Dec2021PricesRs, &item.PercentChangeInDec2021OverDec2020, &item.PercentChangeInDec2021OverSept2021)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetProcurementSupportPrices is the resolver for the getProcurementSupportPrices field.
func (r *queryResolver) GetProcurementSupportPrices(ctx context.Context, year *string) ([]*model.ProcurementSupportPrices, error) {
	query := `SELECT "Year", "Wheat", "Basmati 385", "Basmati Supper", "Irri-6", "Cotton", "Sugarcane" FROM procurement_support_prices_agri_commodities_40kg`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.ProcurementSupportPrices
	for rows.Next() {
		var item model.ProcurementSupportPrices
		err := rows.Scan(&item.Year, &item.Wheat, &item.Basmati385, &item.BasmatiSuper, &item.Irri6, &item.Cotton, &item.Sugarcane)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetProcurementWheatPunjabFoodDept is the resolver for the getProcurementWheatPunjabFoodDept field.
func (r *queryResolver) GetProcurementWheatPunjabFoodDept(ctx context.Context, district *string) ([]*model.ProcurementWheatPunjabFoodDept, error) {
	query := `SELECT "Division / District", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21" FROM procurement_wheat_district_punjab_food_department`
	var args []interface{}
	if district != nil {
		query += ` WHERE "Division / District" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.ProcurementWheatPunjabFoodDept
	for rows.Next() {
		var item model.ProcurementWheatPunjabFoodDept
		err := rows.Scan(&item.DivisionDistrict, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920, &item.Year202021)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetQuantumAcerageIndexImportantCrops is the resolver for the getQuantumAcerageIndexImportantCrops field.
func (r *queryResolver) GetQuantumAcerageIndexImportantCrops(ctx context.Context, crops *string, index *string) ([]*model.QuantumAcerageIndexImportantCrops, error) {
	query := `SELECT "Crops", "Index_ID", "Index", "2011-12", "2012-13", "2013-14", "2014-15", "2015-16", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21" FROM quantum_acerage_index_importaant_crops_2011_21 WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if crops != nil {
		query += ` AND "Crops" = $1`
		args = append(args, *crops)
		argCounter++
	}
	if index != nil {
		query += ` AND "Index" = $2`
		args = append(args, *index)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.QuantumAcerageIndexImportantCrops
	for rows.Next() {
		var item model.QuantumAcerageIndexImportantCrops
		err := rows.Scan(&item.Crops, &item.IndexID, &item.Index, &item.Year201112, &item.Year201213, &item.Year201314, &item.Year201415, &item.Year201516, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920, &item.Year202021)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetRainfallPakistan is the resolver for the getRainfallPakistan field.
func (r *queryResolver) GetRainfallPakistan(ctx context.Context, year *int32, month *string) ([]*model.RainfallPakistan, error) {
	query := `SELECT " Year", "Month", "Rainfall (mm)" FROM rainfall_1901_2016_pakistan WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if year != nil {
		query += ` AND " Year" = $1`
		args = append(args, *year)
		argCounter++
	}
	if month != nil {
		query += ` AND "Month" = $2`
		args = append(args, *month)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.RainfallPakistan
	for rows.Next() {
		var item model.RainfallPakistan
		err := rows.Scan(&item.Year, &item.Month, &item.RainfallMm)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetRainfallSelectedStationsPunjab is the resolver for the getRainfallSelectedStationsPunjab field.
func (r *queryResolver) GetRainfallSelectedStationsPunjab(ctx context.Context, year *int32, month *string) ([]*model.RainfallSelectedStationsPunjab, error) {
	query := `SELECT "Year", "Month", "Bahawalnagar", "Bahawalpur", "Jhelum", "Khanpur", "Lahore", "Multan", "Murree", "Rawalpindi / Islamabad", "Sargodha", "Sialkot" FROM rainfall_selected_stations_punjab_2010_21 WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if year != nil {
		query += ` AND "Year" = $1`
		args = append(args, *year)
		argCounter++
	}
	if month != nil {
		query += ` AND "Month" = $2`
		args = append(args, *month)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.RainfallSelectedStationsPunjab
	for rows.Next() {
		var item model.RainfallSelectedStationsPunjab
		err := rows.Scan(&item.Year, &item.Month, &item.Bahawalnagar, &item.Bahawalpur, &item.Jhelum, &item.Khanpur, &item.Lahore, &item.Multan, &item.Murree, &item.RawalpindiIslamabad, &item.Sargodha, &item.Sialkot)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetSmallDamsPunjab is the resolver for the getSmallDamsPunjab field.
func (r *queryResolver) GetSmallDamsPunjab(ctx context.Context, district *string, tehsil *string) ([]*model.SmallDamsPunjab, error) {
	query := `SELECT "Name of Small Dam", "District", "Tehsil", "Length of Canal (ft)", "Gross Storage Capacity (Aft)", "Actual Irrigation in  Acres" FROM small_dams_district_tehsil_punjab_2018_19 WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if district != nil {
		query += ` AND "District" = $1`
		args = append(args, *district)
		argCounter++
	}
	if tehsil != nil {
		query += ` AND "Tehsil" = $2`
		args = append(args, *tehsil)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.SmallDamsPunjab
	for rows.Next() {
		var item model.SmallDamsPunjab
		err := rows.Scan(&item.NameOfSmallDam, &item.District, &item.Tehsil, &item.LengthOfCanalFt, &item.GrossStorageCapacityAft, &item.ActualIrrigationInAcres)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetSpatialRefSys is the resolver for the getSpatialRefSys field.
func (r *queryResolver) GetSpatialRefSys(ctx context.Context, srid *int32) ([]*model.SpatialRefSys, error) {
	query := `SELECT srid, auth_name, auth_srid, srtext, proj4text FROM spatial_ref_sys`
	var args []interface{}
	if srid != nil {
		query += ` WHERE srid = $1`
		args = append(args, *srid)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.SpatialRefSys
	for rows.Next() {
		var item model.SpatialRefSys
		err := rows.Scan(&item.Srid, &item.AuthName, &item.AuthSrid, &item.Srtext, &item.Proj4text)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetStockWheatPunjabGovt is the resolver for the getStockWheatPunjabGovt field.
func (r *queryResolver) GetStockWheatPunjabGovt(ctx context.Context, month *string) ([]*model.StockWheatPunjabGovt, error) {
	query := `SELECT "Month", "2017-18", "2018-19", "2019-20", "2020-21", "2021-22" FROM stock_wheat_punjab_govt`
	var args []interface{}
	if month != nil {
		query += ` WHERE "Month" = $1`
		args = append(args, *month)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.StockWheatPunjabGovt
	for rows.Next() {
		var item model.StockWheatPunjabGovt
		err := rows.Scan(&item.Month, &item.Year201718, &item.Year201819, &item.Year201920, &item.Year202021, &item.Year202122)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetTemperatureRainTrends is the resolver for the getTemperatureRainTrends field.
func (r *queryResolver) GetTemperatureRainTrends(ctx context.Context, city *string, month *string) ([]*model.TemperatureRainTrends, error) {
	query := `SELECT "Month", "City_ID", "City", "Highest Recorded Temperature in Celsius ", "Highest Recorded Temperature date", "Lowest Recorded Temperature in Celsius mum Temperature in Celsi", "Lowest Recorded Temperature date", "Monthly Heaviest Rainfall in mm", "Heaviest Rainfall date" FROM temperature_rain_trends_major_cities WHERE 1=1`
	var args []interface{}
	argCounter := 1
	if city != nil {
		query += ` AND "City" = $1`
		args = append(args, *city)
		argCounter++
	}
	if month != nil {
		query += ` AND "Month" = $2`
		args = append(args, *month)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.TemperatureRainTrends
	for rows.Next() {
		var item model.TemperatureRainTrends
		err := rows.Scan(&item.Month, &item.CityID, &item.City, &item.HighestRecordedTemperatureInCelsius, &item.HighestRecordedTemperatureDate, &item.LowestRecordedTemperatureInCelsius, &item.LowestRecordedTemperatureDate, &item.MonthlyHeaviestRainfallInMm, &item.HeaviestRainfallDate)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetTractorsImportedPakistan is the resolver for the getTractorsImportedPakistan field.
func (r *queryResolver) GetTractorsImportedPakistan(ctx context.Context, year *string) ([]*model.TractorsImportedPakistan, error) {
	query := `SELECT "Year", "During the Year", "Cumulative Number" FROM tractors_imported_pakistan`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.TractorsImportedPakistan
	for rows.Next() {
		var item model.TractorsImportedPakistan
		err := rows.Scan(&item.Year, &item.DuringTheYear, &item.CumulativeNumber)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetUsageOfFertilizersCropsNutrients is the resolver for the getUsageOfFertilizersCropsNutrients field.
func (r *queryResolver) GetUsageOfFertilizersCropsNutrients(ctx context.Context, year *string) ([]*model.UsageOfFertilizersCropsNutrients, error) {
	query := `SELECT "Year", "Wheat", "Rice", "Maize", "Cotton", "Sugarcane", "Others", "Total" FROM usage_of_fertilizers_crops_nutrients`
	var args []interface{}
	if year != nil {
		query += ` WHERE "Year" = $1`
		args = append(args, *year)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.UsageOfFertilizersCropsNutrients
	for rows.Next() {
		var item model.UsageOfFertilizersCropsNutrients
		err := rows.Scan(&item.Year, &item.Wheat, &item.Rice, &item.Maize, &item.Cotton, &item.Sugarcane, &item.Others, &item.Total)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetUserAccountData is the resolver for the getUserAccountData field.
func (r *queryResolver) GetUserAccountData(ctx context.Context, id *int32, username *string, role *string) ([]*model.UserAccountData, error) {
	query := `SELECT "ID", "Username", "Password", "Email", "Role" FROM user_account_data WHERE 1=1`
	var args []interface{}
	argCounter := 1

	if id != nil {
		query += ` AND "ID" = $` + strconv.Itoa(argCounter)
		args = append(args, *id)
		argCounter++
	}

	if username != nil {
		query += ` AND "Username" = $` + strconv.Itoa(argCounter)
		args = append(args, *username)
		argCounter++
	}

	if role != nil {
		query += ` AND "Role" = $` + strconv.Itoa(argCounter)
		args = append(args, *role)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.UserAccountData
	for rows.Next() {
		var item model.UserAccountData
		err := rows.Scan(&item.ID, &item.Username, &item.Password, &item.Email, &item.Role)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetWaterDeliveryPakistan is the resolver for the getWaterDeliveryPakistan field.
func (r *queryResolver) GetWaterDeliveryPakistan(ctx context.Context, source *string) ([]*model.WaterDeliveryPakistan, error) {
	query := `SELECT "Source", "Urban", "Rural", "Total" FROM water_delivery_pakistan_2013_20`
	var args []interface{}
	if source != nil {
		query += ` WHERE "Source" = $1`
		args = append(args, *source)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.WaterDeliveryPakistan
	for rows.Next() {
		var item model.WaterDeliveryPakistan
		err := rows.Scan(&item.Source, &item.Urban, &item.Rural, &item.Total)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetWatercoursesImprovedDistrictTehsil is the resolver for the getWatercoursesImprovedDistrictTehsil field.
func (r *queryResolver) GetWatercoursesImprovedDistrictTehsil(ctx context.Context, district *string) ([]*model.WatercoursesImprovedDistrictTehsil, error) {
	query := `SELECT "District / Tehsil", "No of Improved Watercourses", "Command Area (Acres)" FROM watercourses_improved_district_tehsil_19_20`
	var args []interface{}
	if district != nil {
		query += ` WHERE "District / Tehsil" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.WatercoursesImprovedDistrictTehsil
	for rows.Next() {
		var item model.WatercoursesImprovedDistrictTehsil
		err := rows.Scan(&item.DistrictTehsil, &item.NoOfImprovedWatercourses, &item.CommandAreaAcres)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetWheatProcurementPunjab is the resolver for the getWheatProcurementPunjab field.
func (r *queryResolver) GetWheatProcurementPunjab(ctx context.Context, district *string) ([]*model.WheatProcurementPunjab, error) {
	query := `SELECT "Division / District", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21" FROM wheat_procurement_punjab_2012_21`
	var args []interface{}
	if district != nil {
		query += ` WHERE "Division / District" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.WheatProcurementPunjab
	for rows.Next() {
		var item model.WheatProcurementPunjab
		err := rows.Scan(&item.DivisionDistrict, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920, &item.Year202021)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetWheatReleaseDistrictPunjab is the resolver for the getWheatReleaseDistrictPunjab field.
func (r *queryResolver) GetWheatReleaseDistrictPunjab(ctx context.Context, district *string) ([]*model.WheatReleaseDistrictPunjab, error) {
	query := `SELECT "Division / District", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21" FROM wheat_release_district_punjab_2016_21`
	var args []interface{}
	if district != nil {
		query += ` WHERE "Division / District" ILIKE $1`
		args = append(args, "%"+*district+"%")
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.WheatReleaseDistrictPunjab
	for rows.Next() {
		var item model.WheatReleaseDistrictPunjab
		err := rows.Scan(&item.DivisionDistrict, &item.Year201617, &item.Year201718, &item.Year201819, &item.Year201920, &item.Year202021)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// GetYearlyCropDataPakistan is the resolver for the getYearlyCropDataPakistan field.
func (r *queryResolver) GetYearlyCropDataPakistan(ctx context.Context, fiscalYear *string) ([]*model.YearlyCropDataPakistan, error) {
	query := `SELECT "Fiscal Year", "Area (Wheat)", "Production (Wheat)", "Yield (Wheat)", "Area (Cotton)", "Production (Cotton)", "Yield (Cotton)", "Area (Suagarcane)", "Production (Suagarcane)", "Yield (Suagarcane)", "Area (Rice)", "Production (Rice)", "Yield (Rice)", "Area (Maize)", "Production (Maize)", "Yield (Maize)" FROM yearly_crop_data_pakistan`
	var args []interface{}
	if fiscalYear != nil {
		query += ` WHERE "Fiscal Year" = $1`
		args = append(args, *fiscalYear)
	}

	rows, err := r.DB.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*model.YearlyCropDataPakistan
	for rows.Next() {
		var item model.YearlyCropDataPakistan
		err := rows.Scan(&item.FiscalYear, &item.AreaWheat, &item.ProductionWheat, &item.YieldWheat, &item.AreaCotton, &item.ProductionCotton, &item.YieldCotton, &item.AreaSugarcane, &item.ProductionSugarcane, &item.YieldSugarcane, &item.AreaRice, &item.ProductionRice, &item.YieldRice, &item.AreaMaize, &item.ProductionMaize, &item.YieldMaize)
		if err != nil {
			return nil, err
		}
		results = append(results, &item)
	}
	return results, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
