// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AdminFarmList struct {
	ID              int32   `json:"id"`
	GroupName       *string `json:"groupName,omitempty"`
	Address         *string `json:"address,omitempty"`
	NumberOfFarms   *int32  `json:"numberOfFarms,omitempty"`
	NumberOfWorkers *int32  `json:"numberOfWorkers,omitempty"`
	Owner           *string `json:"owner,omitempty"`
	Actions         *string `json:"actions,omitempty"`
}

type AdminProjects struct {
	ID        int32    `json:"id"`
	City      *string  `json:"city,omitempty"`
	District  *string  `json:"district,omitempty"`
	Province  *string  `json:"province,omitempty"`
	Address   *string  `json:"address,omitempty"`
	SizeSqm   *float64 `json:"sizeSqm,omitempty"`
	Latitude  *float64 `json:"latitude,omitempty"`
	Longitude *float64 `json:"longitude,omitempty"`
}

type AreaProdOfImportantCrops struct {
	Year                string   `json:"year"`
	AreaWheat           *float64 `json:"areaWheat,omitempty"`
	ProductionWheat     *float64 `json:"productionWheat,omitempty"`
	AreaMaize           *float64 `json:"areaMaize,omitempty"`
	ProductionMaize     *float64 `json:"productionMaize,omitempty"`
	AreaRice            *float64 `json:"areaRice,omitempty"`
	ProductionRice      *float64 `json:"productionRice,omitempty"`
	AreaSugarcane       *float64 `json:"areaSugarcane,omitempty"`
	ProductionSugarcane *float64 `json:"productionSugarcane,omitempty"`
	AreaCotton          *float64 `json:"areaCotton,omitempty"`
	ProductionCotton    *float64 `json:"productionCotton,omitempty"`
}

type AreaProductionKharifVegetablesAjk struct {
	GridID             *int32   `json:"gridId,omitempty"`
	District           string   `json:"district"`
	VegetableID        *int32   `json:"vegetableID,omitempty"`
	Vegetable          *string  `json:"vegetable,omitempty"`
	Area2019Hect       *float64 `json:"area2019Hect,omitempty"`
	Production2019Tons *float64 `json:"production2019Tons,omitempty"`
	Area2020Hect       *float64 `json:"area2020Hect,omitempty"`
	Production2020Tons *float64 `json:"production2020Tons,omitempty"`
	Area2021Hect       *float64 `json:"area2021Hect,omitempty"`
	Production2021Tons *float64 `json:"production2021Tons,omitempty"`
}

type AreaProductionPercentageSharePunjabCrops struct {
	Indicators string   `json:"indicators"`
	CropID     *int32   `json:"cropID,omitempty"`
	Crop       *string  `json:"crop,omitempty"`
	Year200708 *float64 `json:"year200708,omitempty"`
	Year200809 *float64 `json:"year200809,omitempty"`
	Year200910 *float64 `json:"year200910,omitempty"`
	Year201011 *float64 `json:"year201011,omitempty"`
	Year201112 *float64 `json:"year201112,omitempty"`
	Year201213 *float64 `json:"year201213,omitempty"`
	Year201314 *float64 `json:"year201314,omitempty"`
	Year201415 *float64 `json:"year201415,omitempty"`
	Year201516 *float64 `json:"year201516,omitempty"`
	Year201617 *float64 `json:"year201617,omitempty"`
	Year201718 *float64 `json:"year201718,omitempty"`
	Year201819 *float64 `json:"year201819,omitempty"`
	Year201920 *float64 `json:"year201920,omitempty"`
}

type AreaSownBySourceOfIrrigationSindh struct {
	Year       string   `json:"year"`
	Total      *float64 `json:"total,omitempty"`
	Canal      *float64 `json:"canal,omitempty"`
	Well       *float64 `json:"well,omitempty"`
	TubeWell   *float64 `json:"tubeWell,omitempty"`
	CanalWell  *float64 `json:"canalWell,omitempty"`
	CanalWells *float64 `json:"canalWells,omitempty"`
	Others     *float64 `json:"others,omitempty"`
}

type AreaSownIrrigatedImportantCropsPunjab struct {
	Crops      string   `json:"crops"`
	Year201112 *float64 `json:"year201112,omitempty"`
	Year201213 *float64 `json:"year201213,omitempty"`
	Year201314 *float64 `json:"year201314,omitempty"`
	Year201415 *float64 `json:"year201415,omitempty"`
	Year201516 *float64 `json:"year201516,omitempty"`
	Year201617 *float64 `json:"year201617,omitempty"`
	Year201718 *float64 `json:"year201718,omitempty"`
	Year201819 *float64 `json:"year201819,omitempty"`
	Year201920 *float64 `json:"year201920,omitempty"`
	Year202021 *float64 `json:"year202021,omitempty"`
}

type AreaSownIrrigationSource struct {
	Year                      string   `json:"year"`
	TotalAreaSown             *float64 `json:"totalAreaSown,omitempty"`
	UnIrrigated               *float64 `json:"unIrrigated,omitempty"`
	TotalIrrigated            *float64 `json:"totalIrrigated,omitempty"`
	IrrigatedByCanals         *float64 `json:"irrigatedByCanals,omitempty"`
	IrrigatedByWells          *float64 `json:"irrigatedByWells,omitempty"`
	IrrigatedByTubewells      *float64 `json:"irrigatedByTubewells,omitempty"`
	IrrigatedByCanalwells     *float64 `json:"irrigatedByCanalwells,omitempty"`
	IrrigatedByCanalTubewells *float64 `json:"irrigatedByCanalTubewells,omitempty"`
	IrrigatedByOthersSources  *float64 `json:"irrigatedByOthersSources,omitempty"`
}

type AreaSownProdYieldWheatPunjab struct {
	GridID                   *int32   `json:"gridId,omitempty"`
	ProvinceDivisionDistrict string   `json:"provinceDivisionDistrict"`
	Year200708               *float64 `json:"year200708,omitempty"`
	Year200809               *float64 `json:"year200809,omitempty"`
	Year200910               *float64 `json:"year200910,omitempty"`
	Year201011               *float64 `json:"year201011,omitempty"`
	Year201112               *float64 `json:"year201112,omitempty"`
	Year201213               *float64 `json:"year201213,omitempty"`
	Year201314               *float64 `json:"year201314,omitempty"`
	Year201415               *float64 `json:"year201415,omitempty"`
	Year201516               *float64 `json:"year201516,omitempty"`
	Year201617               *float64 `json:"year201617,omitempty"`
	Year201718               *float64 `json:"year201718,omitempty"`
	Year201819               *float64 `json:"year201819,omitempty"`
	Year201920               *float64 `json:"year201920,omitempty"`
}

type AreaSownProductionCropsCombinedPunjab struct {
	Year                            string   `json:"year"`
	CropID                          *int32   `json:"cropID,omitempty"`
	Crop                            *string  `json:"crop,omitempty"`
	TotalAreaSown1000Hects          *float64 `json:"totalAreaSown1000Hects,omitempty"`
	Area1000Hects                   *float64 `json:"area1000Hects,omitempty"`
	Production1000Hects             *float64 `json:"production1000Hects,omitempty"`
	IndexOfAreaSownBaseYear201011   *float64 `json:"indexOfAreaSownBaseYear201011,omitempty"`
	IndexOfProductionBaseYear201011 *float64 `json:"indexOfProductionBaseYear201011,omitempty"`
	PercentShareOfAreaSown          *float64 `json:"percentShareOfAreaSown,omitempty"`
}

type AreaTreatedWithPesticidesCropsPunjab struct {
	Year               string   `json:"year"`
	TotalArea          *float64 `json:"totalArea,omitempty"`
	Wheat              *float64 `json:"wheat,omitempty"`
	RiceAndRiceNursery *float64 `json:"riceAndRiceNursery,omitempty"`
	Cotton             *float64 `json:"cotton,omitempty"`
	Maize              *float64 `json:"maize,omitempty"`
	Sugarcane          *float64 `json:"sugarcane,omitempty"`
	VegetablesFruits   *float64 `json:"vegetablesFruits,omitempty"`
	OtherCrops         *float64 `json:"otherCrops,omitempty"`
}

type AvgRetailPriceFertilizer struct {
	Year     string   `json:"year"`
	Urea     *float64 `json:"urea,omitempty"`
	AnCan26n *float64 `json:"anCan26N,omitempty"`
	As21n    *float64 `json:"as21N,omitempty"`
	Np2022   *float64 `json:"np2022,omitempty"`
	SspG18p  *float64 `json:"sspG18P,omitempty"`
	Dap1846  *float64 `json:"dap1846,omitempty"`
	Sop50k   *float64 `json:"sop50K,omitempty"`
}

type CanalWithdrawlsPunjab struct {
	Year                  string   `json:"year"`
	SeasonID              *int32   `json:"seasonID,omitempty"`
	Season                *string  `json:"season,omitempty"`
	AllCanalsPunjab       *float64 `json:"allCanalsPunjab,omitempty"`
	FiveLinkedCanals      *float64 `json:"fiveLinkedCanals,omitempty"`
	MrLinkInternal        *float64 `json:"mrLinkInternal,omitempty"`
	HaveliCanals          *float64 `json:"haveliCanals,omitempty"`
	PanjnadCanals         *float64 `json:"panjnadCanals,omitempty"`
	CentralBariDoabCanals *float64 `json:"centralBariDoabCanals,omitempty"`
	SutlejValleyCanals    *float64 `json:"sutlejValleyCanals,omitempty"`
	ThalCanals            *float64 `json:"thalCanals,omitempty"`
	TaunsaCanals          *float64 `json:"taunsaCanals,omitempty"`
	Crbc                  *float64 `json:"crbc,omitempty"`
}

type ChannelsLengthDivisionsPunjab struct {
	Division             string   `json:"division"`
	MainCanalsOrBranches *float64 `json:"mainCanalsOrBranches,omitempty"`
	MajorDistributories  *float64 `json:"majorDistributories,omitempty"`
	MinorDistributories  *float64 `json:"minorDistributories,omitempty"`
	SupplyEscapeChannels *float64 `json:"supplyEscapeChannels,omitempty"`
	SubTotal             *float64 `json:"subTotal,omitempty"`
	Drains               *float64 `json:"drains,omitempty"`
	GrandTotal           *float64 `json:"grandTotal,omitempty"`
}

type ConsumptionFertilizersNutrientsPak struct {
	Year      string   `json:"year"`
	KharifN   *float64 `json:"kharifN,omitempty"`
	KharifP   *float64 `json:"kharifP,omitempty"`
	KharifK   *float64 `json:"kharifK,omitempty"`
	KharifAll *float64 `json:"kharifAll,omitempty"`
	RabiN     *float64 `json:"rabiN,omitempty"`
	RabiP     *float64 `json:"rabiP,omitempty"`
	RabiK     *float64 `json:"rabiK,omitempty"`
	RabiAll   *float64 `json:"rabiAll,omitempty"`
	TotalN    *float64 `json:"totalN,omitempty"`
	TotalP    *float64 `json:"totalP,omitempty"`
	TotalK    *float64 `json:"totalK,omitempty"`
	TotalAll  *float64 `json:"totalAll,omitempty"`
}

type ConsumptionOfPesticides struct {
	Year                 string   `json:"year"`
	QuantityMTImports    *float64 `json:"quantityMTImports,omitempty"`
	QuantityMTProduction *float64 `json:"quantityMTProduction,omitempty"`
	QuantityMTTotal      *float64 `json:"quantityMTTotal,omitempty"`
	ValueMillionRs       *float64 `json:"valueMillionRs,omitempty"`
}

type CottonProductionPakistan struct {
	Factor     string   `json:"factor"`
	Year201617 *float64 `json:"year201617,omitempty"`
	Year201718 *float64 `json:"year201718,omitempty"`
	Year201819 *float64 `json:"year201819,omitempty"`
	Year201920 *float64 `json:"year201920,omitempty"`
}

type CropAreaPunjab struct {
	Crop           string   `json:"crop"`
	CroppedArea    *float64 `json:"croppedArea,omitempty"`
	PercentOfTotal *float64 `json:"percentOfTotal,omitempty"`
}

type DashboardData struct {
	Role        string           `json:"role"`
	Statistics  *string          `json:"statistics,omitempty"`
	Permissions []string         `json:"permissions"`
	Pages       []*DashboardPage `json:"pages"`
}

type DashboardPage struct {
	Name             string   `json:"name"`
	AccessibleTables []string `json:"accessibleTables"`
}

type DataLayersManagement struct {
	ID      int32   `json:"id"`
	Name    *string `json:"name,omitempty"`
	Type    *string `json:"type,omitempty"`
	Source  *int32  `json:"source,omitempty"`
	Status  *string `json:"status,omitempty"`
	Actions *string `json:"actions,omitempty"`
}

type DistributionImprovedSeedsPunjab struct {
	Year        string   `json:"year"`
	Wheat       *float64 `json:"wheat,omitempty"`
	Paddy       *float64 `json:"paddy,omitempty"`
	Cotton      *float64 `json:"cotton,omitempty"`
	Maize       *float64 `json:"maize,omitempty"`
	Gram        *float64 `json:"gram,omitempty"`
	Potato      *float64 `json:"potato,omitempty"`
	TotalMetTon *float64 `json:"totalMetTon,omitempty"`
}

type FarmListData struct {
	GroupName       *string `json:"groupName,omitempty"`
	Address         *string `json:"address,omitempty"`
	NumberOfFarms   *int32  `json:"numberOfFarms,omitempty"`
	NumberOfWorkers *int32  `json:"numberOfWorkers,omitempty"`
	Actions         *string `json:"actions,omitempty"`
}

type FarmersTrainedCooperativeFarmingKpk struct {
	Month       string `json:"month"`
	Kohat       *int32 `json:"kohat,omitempty"`
	DiKhan      *int32 `json:"diKhan,omitempty"`
	Mansehra    *int32 `json:"mansehra,omitempty"`
	Hangu       *int32 `json:"hangu,omitempty"`
	Mardan      *int32 `json:"mardan,omitempty"`
	Tank        *int32 `json:"tank,omitempty"`
	Charsadda   *int32 `json:"charsadda,omitempty"`
	Swat        *int32 `json:"swat,omitempty"`
	Peshawar    *int32 `json:"peshawar,omitempty"`
	Shangla     *int32 `json:"shangla,omitempty"`
	Haripur     *int32 `json:"haripur,omitempty"`
	Bannu       *int32 `json:"bannu,omitempty"`
	Chitral     *int32 `json:"chitral,omitempty"`
	Nowshera    *int32 `json:"nowshera,omitempty"`
	DirUpper    *int32 `json:"dirUpper,omitempty"`
	Malakand    *int32 `json:"malakand,omitempty"`
	Abbottabad  *int32 `json:"abbottabad,omitempty"`
	Swabi       *int32 `json:"swabi,omitempty"`
	DirLower    *int32 `json:"dirLower,omitempty"`
	Bunner      *int32 `json:"bunner,omitempty"`
	Karak       *int32 `json:"karak,omitempty"`
	LakkiMarwat *int32 `json:"lakkiMarwat,omitempty"`
	Battagram   *int32 `json:"battagram,omitempty"`
	Torghar     *int32 `json:"torghar,omitempty"`
	Kohistan    *int32 `json:"kohistan,omitempty"`
}

type FertilizerMachineryImpactKpk struct {
	GridID    *int32   `json:"gridId,omitempty"`
	Year      string   `json:"year"`
	Factors   *string  `json:"factors,omitempty"`
	SubFactor *string  `json:"subFactor,omitempty"`
	Districts *string  `json:"districts,omitempty"`
	Amount    *float64 `json:"amount,omitempty"`
}

type FertilizerUsageProductionPunjab struct {
	GridID                  *int32   `json:"gridId,omitempty"`
	Year                    string   `json:"year"`
	Province                *string  `json:"province,omitempty"`
	Division                *string  `json:"division,omitempty"`
	District                *string  `json:"district,omitempty"`
	UsageIn1000NutrientTons *int32   `json:"usageIn1000NutrientTons,omitempty"`
	AreaSownTotalWheat      *int32   `json:"areaSownTotalWheat,omitempty"`
	AreaSownRice            *int32   `json:"areaSownRice,omitempty"`
	AreaSownCotton          *int32   `json:"areaSownCotton,omitempty"`
	AreaSownSugarcane       *int32   `json:"areaSownSugarcane,omitempty"`
	WheatProduction         *int32   `json:"wheatProduction,omitempty"`
	RiceProduction          *int32   `json:"riceProduction,omitempty"`
	CottonProduction        *int32   `json:"cottonProduction,omitempty"`
	SugarcaneProduction     *int32   `json:"sugarcaneProduction,omitempty"`
	OutputAcreWheat         *float64 `json:"outputAcreWheat,omitempty"`
	OutputAcreRice          *float64 `json:"outputAcreRice,omitempty"`
	OutputAcreCotton        *float64 `json:"outputAcreCotton,omitempty"`
	OutputAcreSugarcane     *float64 `json:"outputAcreSugarcane,omitempty"`
}

type FertilizersSaleDistrictsPunjab struct {
	GridID           *int32 `json:"gridId,omitempty"`
	DivisionDistrict string `json:"divisionDistrict"`
	Year201516       *int32 `json:"year201516,omitempty"`
	Year201617       *int32 `json:"year201617,omitempty"`
	Year201718       *int32 `json:"year201718,omitempty"`
	Year201819       *int32 `json:"year201819,omitempty"`
	Year201920       *int32 `json:"year201920,omitempty"`
}

type FoodGrainsStorageCapacityPunjab struct {
	GridID             *int32   `json:"gridId,omitempty"`
	DivisionDistrict   string   `json:"divisionDistrict"`
	HouseType          *float64 `json:"houseType,omitempty"`
	SilosBinsBiniShell *float64 `json:"silosBinsBiniShell,omitempty"`
	OpenBulkHeads      *float64 `json:"openBulkHeads,omitempty"`
	Total              *float64 `json:"total,omitempty"`
}

type ForestsProductsPakistan struct {
	Year                      string   `json:"year"`
	TimberThousandCubMeters   *float64 `json:"timberThousandCubMeters,omitempty"`
	FirewoodThousandCubMeters *float64 `json:"firewoodThousandCubMeters,omitempty"`
	TotalThousandCubMeters    *float64 `json:"totalThousandCubMeters,omitempty"`
	TimberMillionRupees       *float64 `json:"timberMillionRupees,omitempty"`
	FirewoodMillionRupees     *float64 `json:"firewoodMillionRupees,omitempty"`
	TotalMillionRupees        *float64 `json:"totalMillionRupees,omitempty"`
}

type ForgetPassword struct {
	ID       string  `json:"id"`
	UserID   int32   `json:"userId"`
	Email    *string `json:"email,omitempty"`
	Token    string  `json:"token"`
	ExpireAt string  `json:"expire_at"`
	Used     bool    `json:"used"`
	Created  string  `json:"created"`
}

type GeographyColumns struct {
	FTableCatalog    *string `json:"fTableCatalog,omitempty"`
	FTableSchema     *string `json:"fTableSchema,omitempty"`
	FTableName       *string `json:"fTableName,omitempty"`
	FGeographyColumn *string `json:"fGeographyColumn,omitempty"`
	CoordDimension   *int32  `json:"coordDimension,omitempty"`
	Srid             *int32  `json:"srid,omitempty"`
	Type             *string `json:"type,omitempty"`
}

type GeometryColumns struct {
	FTableCatalog   *string `json:"fTableCatalog,omitempty"`
	FTableSchema    *string `json:"fTableSchema,omitempty"`
	FTableName      *string `json:"fTableName,omitempty"`
	FGeometryColumn *string `json:"fGeometryColumn,omitempty"`
	CoordDimension  *int32  `json:"coordDimension,omitempty"`
	Srid            *int32  `json:"srid,omitempty"`
	Type            *string `json:"type,omitempty"`
}

type GroundTruthingSurveyAdb struct {
	ID          string   `json:"id"`
	GridID      *int32   `json:"gridId,omitempty"`
	Season      *string  `json:"season,omitempty"`
	Province    *string  `json:"province,omitempty"`
	District    *string  `json:"district,omitempty"`
	Date        *string  `json:"date,omitempty"`
	Latitude    *float64 `json:"latitude,omitempty"`
	Longitude   *float64 `json:"longitude,omitempty"`
	Code        *int32   `json:"code,omitempty"`
	Land        *string  `json:"land,omitempty"`
	Description *string  `json:"description,omitempty"`
	Stage       *string  `json:"stage,omitempty"`
}

type GroupListData struct {
	Username string  `json:"username"`
	Email    *string `json:"email,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Role     *string `json:"role,omitempty"`
	Status   *bool   `json:"status,omitempty"`
	Joined   *string `json:"joined,omitempty"`
}

type KharifRabiIrrigatedCrop struct {
	Crop              string   `json:"crop"`
	TotalIn201819     *float64 `json:"totalIn201819,omitempty"`
	IrrigatedIn201819 *float64 `json:"irrigatedIn201819,omitempty"`
	TotalIn201920     *float64 `json:"totalIn201920,omitempty"`
	IrrigatedIn201920 *float64 `json:"irrigatedIn201920,omitempty"`
	TotalIn202021     *float64 `json:"totalIn202021,omitempty"`
	Irrigated202021   *float64 `json:"irrigated202021,omitempty"`
}

type LandUtilizationStatisticsPunjab struct {
	Year                            string  `json:"year"`
	GridID                          *int32  `json:"gridId,omitempty"`
	ProvinceDivisionDistrict        *string `json:"provinceDivisionDistrict,omitempty"`
	GeographicalArea                *int32  `json:"geographicalArea,omitempty"`
	ReportedArea                    *int32  `json:"reportedArea,omitempty"`
	TotalCultivatedArea             *int32  `json:"totalCultivatedArea,omitempty"`
	CurrentFallowsCultivatedArea    *int32  `json:"currentFallowsCultivatedArea,omitempty"`
	NetAreaSown                     *int32  `json:"netAreaSown,omitempty"`
	TotalCroppedArea                *int32  `json:"totalCroppedArea,omitempty"`
	AreaSownMoreThanOnce            *int32  `json:"areaSownMoreThanOnce,omitempty"`
	TotalUncultivatedArea           *int32  `json:"totalUncultivatedArea,omitempty"`
	CulturableWasteUncultivatedArea *int32  `json:"culturableWasteUncultivatedArea,omitempty"`
	ForestUncultivatedArea          *int32  `json:"forestUncultivatedArea,omitempty"`
	NotAvailableForCultivation      *int32  `json:"notAvailableForCultivation,omitempty"`
}

type LoansDisbursedZaraiTaraqiatBank struct {
	Purpose    string `json:"purpose"`
	Year201617 *int32 `json:"year201617,omitempty"`
	Year201718 *int32 `json:"year201718,omitempty"`
	Year201819 *int32 `json:"year201819,omitempty"`
	Year201920 *int32 `json:"year201920,omitempty"`
	Year202021 *int32 `json:"year202021,omitempty"`
}

type LoginResponse struct {
	Success bool             `json:"success"`
	Message string           `json:"message"`
	Token   *string          `json:"token,omitempty"`
	User    *UserAccountData `json:"user,omitempty"`
}

type LogoutResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type MauzzasCroppedAreaPunjab struct {
	DivisionDistrict        string `json:"divisionDistrict"`
	NumberOfMauzas          *int32 `json:"numberOfMauzas,omitempty"`
	CroppedArea1000Hectares *int32 `json:"croppedArea1000Hectares,omitempty"`
	GridID                  *int32 `json:"gridId,omitempty"`
}

type Mutation struct {
}

type PasswordResetResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type PasswordResetValidation struct {
	Valid   bool   `json:"valid"`
	Message string `json:"message"`
	UserID  *int32 `json:"userId,omitempty"`
}

type PercentageDistributionWheatPunjab struct {
	ProvinceDivisionDistrict string   `json:"provinceDivisionDistrict"`
	GridID                   *int32   `json:"gridId,omitempty"`
	Year200708               *float64 `json:"year200708,omitempty"`
	Year200809               *float64 `json:"year200809,omitempty"`
	Year200910               *float64 `json:"year200910,omitempty"`
	Year201011               *float64 `json:"year201011,omitempty"`
	Year201112               *float64 `json:"year201112,omitempty"`
	Year201213               *float64 `json:"year201213,omitempty"`
	Year201314               *float64 `json:"year201314,omitempty"`
	Year201415               *float64 `json:"year201415,omitempty"`
	Year201516               *float64 `json:"year201516,omitempty"`
	Year201617               *float64 `json:"year201617,omitempty"`
	Year201718               *float64 `json:"year201718,omitempty"`
	Year201819               *float64 `json:"year201819,omitempty"`
	Year201920               *float64 `json:"year201920,omitempty"`
}

type PredictionCropYieldRiskPunjab struct {
	DivisionDistrict   string `json:"divisionDistrict"`
	GridID             *int32 `json:"gridId,omitempty"`
	Wheat              *int32 `json:"wheat,omitempty"`
	Gram               *int32 `json:"gram,omitempty"`
	Barley             *int32 `json:"barley,omitempty"`
	Potato             *int32 `json:"potato,omitempty"`
	Onion              *int32 `json:"onion,omitempty"`
	Canola             *int32 `json:"canola,omitempty"`
	RapeseedAndMustard *int32 `json:"rapeseedAndMustard,omitempty"`
	MasoorCrop         *int32 `json:"masoorCrop,omitempty"`
	MattarPeas         *int32 `json:"mattarPeas,omitempty"`
	OtherRabiPulses    *int32 `json:"otherRabiPulses,omitempty"`
	Garlic             *int32 `json:"garlic,omitempty"`
	Tabacco            *int32 `json:"tabacco,omitempty"`
	Linseed            *int32 `json:"linseed,omitempty"`
	Corriander         *int32 `json:"corriander,omitempty"`
	MattarGreen        *int32 `json:"mattarGreen,omitempty"`
	Carrot             *int32 `json:"carrot,omitempty"`
	Tomato             *int32 `json:"tomato,omitempty"`
	Turnip             *int32 `json:"turnip,omitempty"`
	Cauliflower        *int32 `json:"cauliflower,omitempty"`
	OtherVegetables    *int32 `json:"otherVegetables,omitempty"`
	Guava              *int32 `json:"guava,omitempty"`
	Banana             *int32 `json:"banana,omitempty"`
	Grapefruit         *int32 `json:"grapefruit,omitempty"`
	Kinnu              *int32 `json:"kinnu,omitempty"`
	Lemon              *int32 `json:"lemon,omitempty"`
	Mandrine           *int32 `json:"mandrine,omitempty"`
	Orange             *int32 `json:"orange,omitempty"`
	Musumbi            *int32 `json:"musumbi,omitempty"`
	SourLime           *int32 `json:"sourLime,omitempty"`
	SourOrange         *int32 `json:"sourOrange,omitempty"`
	SweetLime          *int32 `json:"sweetLime,omitempty"`
	OtherCitrus        *int32 `json:"otherCitrus,omitempty"`
	Ber                *int32 `json:"ber,omitempty"`
	Loquat             *int32 `json:"loquat,omitempty"`
	Mulberry           *int32 `json:"mulberry,omitempty"`
	OtherRabiFruits    *int32 `json:"otherRabiFruits,omitempty"`
	Barseem            *int32 `json:"barseem,omitempty"`
	Lucern             *int32 `json:"lucern,omitempty"`
	Others             *int32 `json:"others,omitempty"`
}

type PriceWheatCities struct {
	CommodityItem                      string   `json:"commodityItem"`
	GridID                             *int32   `json:"gridId,omitempty"`
	UnitKg                             *int32   `json:"unitKg,omitempty"`
	City                               *string  `json:"city,omitempty"`
	Dec2020PricesRs                    *float64 `json:"dec2020PricesRs,omitempty"`
	Sept2021PricesRs                   *float64 `json:"sept2021PricesRs,omitempty"`
	Dec2021PricesRs                    *float64 `json:"dec2021PricesRs,omitempty"`
	PercentChangeInDec2021OverDec2020  *float64 `json:"percentChangeInDec2021OverDec2020,omitempty"`
	PercentChangeInDec2021OverSept2021 *float64 `json:"percentChangeInDec2021OverSept2021,omitempty"`
}

type ProcurementSupportPrices struct {
	Year         string `json:"year"`
	Wheat        *int32 `json:"wheat,omitempty"`
	Basmati385   *int32 `json:"basmati385,omitempty"`
	BasmatiSuper *int32 `json:"basmatiSuper,omitempty"`
	Irri6        *int32 `json:"irri6,omitempty"`
	Cotton       *int32 `json:"cotton,omitempty"`
	Sugarcane    *int32 `json:"sugarcane,omitempty"`
}

type ProcurementWheatPunjabFoodDept struct {
	DivisionDistrict string `json:"divisionDistrict"`
	GridID           *int32 `json:"gridId,omitempty"`
	Year201617       *int32 `json:"year201617,omitempty"`
	Year201718       *int32 `json:"year201718,omitempty"`
	Year201819       *int32 `json:"year201819,omitempty"`
	Year201920       *int32 `json:"year201920,omitempty"`
	Year202021       *int32 `json:"year202021,omitempty"`
}

type QuantumAcerageIndexImportantCrops struct {
	Crops      string   `json:"crops"`
	IndexID    *int32   `json:"indexID,omitempty"`
	Index      *string  `json:"index,omitempty"`
	Year201112 *float64 `json:"year201112,omitempty"`
	Year201213 *float64 `json:"year201213,omitempty"`
	Year201314 *float64 `json:"year201314,omitempty"`
	Year201415 *float64 `json:"year201415,omitempty"`
	Year201516 *float64 `json:"year201516,omitempty"`
	Year201617 *float64 `json:"year201617,omitempty"`
	Year201718 *float64 `json:"year201718,omitempty"`
	Year201819 *float64 `json:"year201819,omitempty"`
	Year201920 *float64 `json:"year201920,omitempty"`
	Year202021 *float64 `json:"year202021,omitempty"`
}

type Query struct {
}

type RainfallPakistan struct {
	Year       int32    `json:"year"`
	Month      string   `json:"month"`
	RainfallMm *float64 `json:"rainfallMm,omitempty"`
}

type RainfallSelectedStationsPunjab struct {
	Year                int32    `json:"year"`
	Month               string   `json:"month"`
	Bahawalnagar        *float64 `json:"bahawalnagar,omitempty"`
	Bahawalpur          *float64 `json:"bahawalpur,omitempty"`
	Jhelum              *float64 `json:"jhelum,omitempty"`
	Khanpur             *float64 `json:"khanpur,omitempty"`
	Lahore              *float64 `json:"lahore,omitempty"`
	Multan              *float64 `json:"multan,omitempty"`
	Murree              *float64 `json:"murree,omitempty"`
	RawalpindiIslamabad *float64 `json:"rawalpindiIslamabad,omitempty"`
	Sargodha            *float64 `json:"sargodha,omitempty"`
	Sialkot             *float64 `json:"sialkot,omitempty"`
}

type SmallDamsPunjab struct {
	NameOfSmallDam          string  `json:"nameOfSmallDam"`
	District                *string `json:"district,omitempty"`
	Tehsil                  *string `json:"tehsil,omitempty"`
	LengthOfCanalFt         *int32  `json:"lengthOfCanalFt,omitempty"`
	GrossStorageCapacityAft *int32  `json:"grossStorageCapacityAft,omitempty"`
	ActualIrrigationInAcres *int32  `json:"actualIrrigationInAcres,omitempty"`
}

type SpatialRefSys struct {
	Srid      int32   `json:"srid"`
	AuthName  *string `json:"authName,omitempty"`
	AuthSrid  *int32  `json:"authSrid,omitempty"`
	Srtext    *string `json:"srtext,omitempty"`
	Proj4text *string `json:"proj4text,omitempty"`
}

type StockWheatPunjabGovt struct {
	Month      string `json:"month"`
	Year201718 *int32 `json:"year201718,omitempty"`
	Year201819 *int32 `json:"year201819,omitempty"`
	Year201920 *int32 `json:"year201920,omitempty"`
	Year202021 *int32 `json:"year202021,omitempty"`
	Year202122 *int32 `json:"year202122,omitempty"`
}

type TemperatureRainTrends struct {
	Month                               string   `json:"month"`
	GridID                              *int32   `json:"gridId,omitempty"`
	CityID                              *int32   `json:"cityID,omitempty"`
	City                                *string  `json:"city,omitempty"`
	HighestRecordedTemperatureInCelsius *float64 `json:"highestRecordedTemperatureInCelsius,omitempty"`
	HighestRecordedTemperatureDate      *string  `json:"highestRecordedTemperatureDate,omitempty"`
	LowestRecordedTemperatureInCelsius  *float64 `json:"lowestRecordedTemperatureInCelsius,omitempty"`
	LowestRecordedTemperatureDate       *string  `json:"lowestRecordedTemperatureDate,omitempty"`
	MonthlyHeaviestRainfallInMm         *float64 `json:"monthlyHeaviestRainfallInMm,omitempty"`
	HeaviestRainfallDate                *int32   `json:"heaviestRainfallDate,omitempty"`
}

type TractorsImportedPakistan struct {
	Year             string `json:"year"`
	DuringTheYear    *int32 `json:"duringTheYear,omitempty"`
	CumulativeNumber *int32 `json:"cumulativeNumber,omitempty"`
}

type UsageOfFertilizersCropsNutrients struct {
	Year      string   `json:"year"`
	Wheat     *float64 `json:"wheat,omitempty"`
	Rice      *float64 `json:"rice,omitempty"`
	Maize     *float64 `json:"maize,omitempty"`
	Cotton    *float64 `json:"cotton,omitempty"`
	Sugarcane *float64 `json:"sugarcane,omitempty"`
	Others    *float64 `json:"others,omitempty"`
	Total     *float64 `json:"total,omitempty"`
}

type UserAccountData struct {
	ID       int32   `json:"id"`
	Username *string `json:"username,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Role     *string `json:"role,omitempty"`
	Status   *bool   `json:"status,omitempty"`
	Joined   *string `json:"joined,omitempty"`
}

type UserProjectData struct {
	Latitude  float64  `json:"latitude"`
	Longitude float64  `json:"longitude"`
	Region    *string  `json:"region,omitempty"`
	City      *string  `json:"city,omitempty"`
	District  *string  `json:"district,omitempty"`
	Address   *string  `json:"address,omitempty"`
	SizeSqm   *float64 `json:"sizeSqm,omitempty"`
}

type WaterDeliveryPakistan struct {
	Source string   `json:"source"`
	Urban  *float64 `json:"urban,omitempty"`
	Rural  *float64 `json:"rural,omitempty"`
	Total  *float64 `json:"total,omitempty"`
}

type WatercoursesImprovedDistrictTehsil struct {
	DistrictTehsil           string   `json:"districtTehsil"`
	NoOfImprovedWatercourses *float64 `json:"noOfImprovedWatercourses,omitempty"`
	CommandAreaAcres         *float64 `json:"commandAreaAcres,omitempty"`
}

type WheatProcurementPunjab struct {
	DivisionDistrict string `json:"divisionDistrict"`
	GridID           *int32 `json:"gridId,omitempty"`
	Year201617       *int32 `json:"year201617,omitempty"`
	Year201718       *int32 `json:"year201718,omitempty"`
	Year201819       *int32 `json:"year201819,omitempty"`
	Year201920       *int32 `json:"year201920,omitempty"`
	Year202021       *int32 `json:"year202021,omitempty"`
}

type WheatReleaseDistrictPunjab struct {
	DivisionDistrict string `json:"divisionDistrict"`
	GridID           *int32 `json:"gridId,omitempty"`
	Year201617       *int32 `json:"year201617,omitempty"`
	Year201718       *int32 `json:"year201718,omitempty"`
	Year201819       *int32 `json:"year201819,omitempty"`
	Year201920       *int32 `json:"year201920,omitempty"`
	Year202021       *int32 `json:"year202021,omitempty"`
}

type YearlyCropDataPakistan struct {
	FiscalYear          string   `json:"fiscalYear"`
	AreaWheat           *float64 `json:"areaWheat,omitempty"`
	ProductionWheat     *float64 `json:"productionWheat,omitempty"`
	YieldWheat          *float64 `json:"yieldWheat,omitempty"`
	AreaCotton          *float64 `json:"areaCotton,omitempty"`
	ProductionCotton    *float64 `json:"productionCotton,omitempty"`
	YieldCotton         *float64 `json:"yieldCotton,omitempty"`
	AreaSugarcane       *float64 `json:"areaSugarcane,omitempty"`
	ProductionSugarcane *float64 `json:"productionSugarcane,omitempty"`
	YieldSugarcane      *float64 `json:"yieldSugarcane,omitempty"`
	AreaRice            *float64 `json:"areaRice,omitempty"`
	ProductionRice      *float64 `json:"productionRice,omitempty"`
	YieldRice           *float64 `json:"yieldRice,omitempty"`
	AreaMaize           *float64 `json:"areaMaize,omitempty"`
	ProductionMaize     *float64 `json:"productionMaize,omitempty"`
	YieldMaize          *float64 `json:"yieldMaize,omitempty"`
}
